-- return {
-- 	'nvim-neo-tree/neo-tree.nvim',
-- 	branch = 'v3.x',
-- 	dependencies = {
-- 		'nvim-lua/plenary.nvim',
-- 		'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
-- 		'MunifTanjim/nui.nvim',
-- 	},
-- 	lazy = false, -- neo-tree will lazily load itself
-- 	---@module "neo-tree"
-- 	---@type neotree.Config?
-- 	opts = {
-- 		keys = {
-- 			{ '<C-n>', ':Neotree toggle left<CR>', desc = 'Neotree Toggle', silent = true },
-- 		},
-- 		filesystem = {
-- 			filtered_items = {
-- 				visible = true,
-- 				always_show = { 'build' },
-- 			},
-- 		},
-- 	},
-- }
